#include "stdafx.h"
#include "weaponWeapons.h"
#include "../weaponMenu.h"

using namespace WeaponWeaponsMenuVars;

namespace WeaponWeaponsMenuVars {
	Vars vars;

	ScrollStruct<int> camoScrollStruct[] = {
		TranslationString("Default", true), 0,
		TranslationString("Green", true), 1,
		TranslationString("Gold", true), 2,
		TranslationString("Pink", true), 3,
		TranslationString("Army", true), 4,
		TranslationString("LSPD", true), 5,
		TranslationString("Orange", true), 6,
		TranslationString("Platinum", true), 7,
	};

	enum eWeaponComponentHashes : Hash {
		COMPONENT_ADVANCEDRIFLE_CLIP_01 = 0xFA8FA10F,
		COMPONENT_ADVANCEDRIFLE_CLIP_02 = 0x8EC1C979,
		COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE = 0x377CD377,
		COMPONENT_APPISTOL_CLIP_01 = 0x31C4B22A,
		COMPONENT_APPISTOL_CLIP_02 = 0x249A17D5,
		COMPONENT_APPISTOL_VARMOD_LUXE = 0x9B76C72C,
		COMPONENT_ASSAULTRIFLE_CLIP_01 = 0xBE5EEA16,
		COMPONENT_ASSAULTRIFLE_CLIP_02 = 0xB1214F9B,
		COMPONENT_ASSAULTRIFLE_CLIP_03 = 0xDBF0A53D,
		COMPONENT_ASSAULTRIFLE_VARMOD_LUXE = 0x4EAD7533,
		COMPONENT_ASSAULTSHOTGUN_CLIP_01 = 0x94E81BC7,
		COMPONENT_ASSAULTSHOTGUN_CLIP_02 = 0x86BD7F72,
		COMPONENT_ASSAULTSMG_CLIP_01 = 0x8D1307B0,
		COMPONENT_ASSAULTSMG_CLIP_02 = 0xBB46E417,
		COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER = 0x278C78AF,
		COMPONENT_AT_AR_AFGRIP = 0xC164F53,
		COMPONENT_AT_AR_FLSH = 0x7BC4CDDC,
		COMPONENT_AT_AR_SUPP = 0x837445AA,
		COMPONENT_AT_AR_SUPP_02 = 0xA73D4664,
		COMPONENT_AT_PI_FLSH = 0x359B7AAE,
		COMPONENT_AT_PI_SUPP = 0xC304849A,
		COMPONENT_AT_PI_SUPP_02 = 0x65EA7EBB,
		COMPONENT_AT_RAILCOVER_01 = 0x75414F30,
		COMPONENT_AT_SCOPE_LARGE = 0xD2443DDC,
		COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM = 0x1C221B1A,
		COMPONENT_AT_SCOPE_MACRO = 0x9D2FBF29,
		COMPONENT_AT_SCOPE_MACRO_02 = 0x3CC6BA57,
		COMPONENT_AT_SCOPE_MAX = 0xBC54DA77,
		COMPONENT_AT_SCOPE_MEDIUM = 0xA0D89C42,
		COMPONENT_AT_SCOPE_SMALL = 0xAA2C45B4,
		COMPONENT_AT_SCOPE_SMALL_02 = 0x3C00AFED,
		COMPONENT_AT_SR_SUPP = 0xE608B35E,
		COMPONENT_AT_SCOPE_LARGE_MK2 = 0x82C10383,
		COMPONENT_AT_SCOPE_NV = 0xB68010B0,
		COMPONENT_AT_SCOPE_THERMAL = 0x2E43DA41,
		COMPONENT_AT_SR_SUPP_03 = 0xAC42DF71,
		COMPONENT_AT_MUZZLE_08 = 0x5F7DCE4D,
		COMPONENT_AT_MUZZLE_09 = 0x6927E1A1,
		COMPONENT_AT_SR_BARREL_01 = 0x909630B7,
		COMPONENT_AT_SR_BARREL_02 = 0x108AB09E,
		COMPONENT_AT_SCOPE_SMALL_MK2 = 0x3F3C8181,
		COMPONENT_AT_MG_BARREL_01 = 0xC34EF234,
		COMPONENT_AT_MG_BARREL_02 = 0xB5E2575B,
		COMPONENT_AT_SIGHTS_SMG = 0x9FDB5652,
		COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2 = 0xE502AB6B,
		COMPONENT_AT_SCOPE_SMALL_SMG_MK2 = 0x3DECC7DA,
		COMPONENT_AT_MUZZLE_01 = 0xB99402D4,
		COMPONENT_AT_MUZZLE_02 = 0xC867A07B,
		COMPONENT_AT_MUZZLE_03 = 0xDE11CBCF,
		COMPONENT_AT_MUZZLE_04 = 0xEC9068CC,
		COMPONENT_AT_MUZZLE_05 = 0x2E7957A,
		COMPONENT_AT_MUZZLE_06 = 0x347EF8AC,
		COMPONENT_AT_MUZZLE_07 = 0x4DB62ABE,
		COMPONENT_AT_SB_BARREL_01 = 0xD9103EE1,
		COMPONENT_AT_SB_BARREL_02 = 0xA564D78B,
		COMPONENT_AT_PI_RAIL = 0x8ED4BB70,
		COMPONENT_AT_PI_FLSH_02 = 0x43FD595B,
		COMPONENT_AT_PI_COMP = 0x21E34793,
		COMPONENT_AT_AR_AFGRIP_02 = 0x9D65907A,
		COMPONENT_AT_SIGHTS = 0x420FD713,
		COMPONENT_AT_SCOPE_MACRO_MK2 = 0x49B2945,
		COMPONENT_AT_SCOPE_MEDIUM_MK2 = 0xC66B6542,
		COMPONENT_AT_AR_BARREL_01 = 0x43A49D26,
		COMPONENT_AT_AR_BARREL_02 = 0x5646C26A,
		COMPONENT_AT_CR_BARREL_01 = 0x833637FF,
		COMPONENT_AT_CR_BARREL_02 = 0x8B3C480B,
		COMPONENT_CARBINERIFLE_CLIP_01 = 0x9FBE33EC,
		COMPONENT_CARBINERIFLE_CLIP_02 = 0x91109691,
		COMPONENT_CARBINERIFLE_CLIP_03 = 0xBA62E935,
		COMPONENT_CARBINERIFLE_VARMOD_LUXE = 0xD89B9658,
		COMPONENT_COMBATMG_CLIP_01 = 0xE1FFB34A,
		COMPONENT_COMBATMG_CLIP_02 = 0xD6C59CD6,
		COMPONENT_COMBATMG_VARMOD_LOWRIDER = 0x92FECCDD,
		COMPONENT_COMBATPISTOL_CLIP_01 = 0x721B079,
		COMPONENT_COMBATPISTOL_CLIP_02 = 0xD67B4F2D,
		COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER = 0xC6654D72,
		COMPONENT_HEAVYSNIPER_CLIP_01 = 0x476F52F4,
		COMPONENT_MG_CLIP_01 = 0xF434EF84,
		COMPONENT_MG_CLIP_02 = 0x82158B47,
		COMPONENT_MG_VARMOD_LOWRIDER = 0xD6DABABE,
		COMPONENT_MICROSMG_CLIP_01 = 0xCB48AEF0,
		COMPONENT_MICROSMG_CLIP_02 = 0x10E6BA2B,
		COMPONENT_MICROSMG_VARMOD_LUXE = 0x487AAE09,
		COMPONENT_MINIGUN_CLIP_01 = 0xC8DE6F06,
		COMPONENT_PISTOL50_CLIP_01 = 0x2297BE19,
		COMPONENT_PISTOL50_CLIP_02 = 0xD9D3AC92,
		COMPONENT_PISTOL50_VARMOD_LUXE = 0x77B8AB2F,
		COMPONENT_PISTOL_CLIP_01 = 0xFED0FD71,
		COMPONENT_PISTOL_CLIP_02 = 0xED265A1C,
		COMPONENT_PISTOL_VARMOD_LUXE = 0xD7391086,
		COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER = 0xA2D79DDB,
		COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE = 0x85A64DF9,
		COMPONENT_SMG_CLIP_01 = 0x26574997,
		COMPONENT_SMG_CLIP_02 = 0x350966FB,
		COMPONENT_SMG_CLIP_03 = 0x79C77076,
		COMPONENT_SMG_VARMOD_LUXE = 0x27872C90,
		COMPONENT_SNIPERRIFLE_CLIP_01 = 0x9BC64089,
		COMPONENT_SNIPERRIFLE_VARMOD_LUXE = 0x4032B5E7,

		// ----------------DLC Weapons----------------

		// Beach Bum Update:

		COMPONENT_SNSPISTOL_CLIP_01 = 0xF8802ED9,
		COMPONENT_SNSPISTOL_CLIP_02 = 0x7B0033B3,
		COMPONENT_SNSPISTOL_VARMOD_LOWRIDER = 0x8033ECAF,

		// Valentines Day Massacre Special:

		COMPONENT_GUSENBERG_CLIP_01 = 0x1CE5A6A5,
		COMPONENT_GUSENBERG_CLIP_02 = 0xEAC8C270,

		// Business Update:

		COMPONENT_SPECIALCARBINE_CLIP_01 = 0xC6C7E581,
		COMPONENT_SPECIALCARBINE_CLIP_02 = 0x7C8BD10E,
		COMPONENT_SPECIALCARBINE_CLIP_03 = 0x6B59AEAA,
		COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER = 0x730154F2,
		COMPONENT_HEAVYPISTOL_CLIP_01 = 0xD4A969A,
		COMPONENT_HEAVYPISTOL_CLIP_02 = 0x64F9C62B,
		COMPONENT_HEAVYPISTOL_VARMOD_LUXE = 0x7A6A7B7B,

		// High Life Update:

		COMPONENT_BULLPUPRIFLE_CLIP_01 = 0xC5A12F80,
		COMPONENT_BULLPUPRIFLE_CLIP_02 = 0xB3688B0F,
		COMPONENT_BULLPUPRIFLE_VARMOD_LOW = 0xA857BC78,

		// "I'm Not a Hipster" Update:

		COMPONENT_VINTAGEPISTOL_CLIP_01 = 0x45A3B6BB,
		COMPONENT_VINTAGEPISTOL_CLIP_02 = 0x33BA12E8,

		// Independence Day Special: None

		// Last Team Standing Update:

		COMPONENT_HEAVYSHOTGUN_CLIP_01 = 0x324F2D5F,
		COMPONENT_HEAVYSHOTGUN_CLIP_02 = 0x971CF6FD,
		COMPONENT_HEAVYSHOTGUN_CLIP_03 = 0x88C7DA53,
		COMPONENT_MARKSMANRIFLE_CLIP_01 = 0xD83B4141,
		COMPONENT_MARKSMANRIFLE_CLIP_02 = 0xCCFD2AC5,
		COMPONENT_MARKSMANRIFLE_VARMOD_LUXE = 0x161E9241,

		// Festive Surprise: None

		// Heists Update: None

		// Ill-Gotten Gains Part 1:

		COMPONENT_COMBATPDW_CLIP_01 = 0x4317F19E,
		COMPONENT_COMBATPDW_CLIP_02 = 0x334A5203,
		COMPONENT_COMBATPDW_CLIP_03 = 0x6EB8C8DB,

		// Ill-Gotten Gains Part 2:

		COMPONENT_MARKSMANPISTOL_CLIP_01 = 0xCB9E41ED,
		COMPONENT_KNUCKLE_VARMOD_BASE = 0xF3462F33,
		COMPONENT_KNUCKLE_VARMOD_BALLAS = 0xEED9FD63,
		COMPONENT_KNUCKLE_VARMOD_DIAMOND = 0x9761D9DC,
		COMPONENT_KNUCKLE_VARMOD_DOLLAR = 0x50910C31,
		COMPONENT_KNUCKLE_VARMOD_HATE = 0x7DECFE30,
		COMPONENT_KNUCKLE_VARMOD_KING = 0xE28BABEF,
		COMPONENT_KNUCKLE_VARMOD_LOVE = 0x3F4E8AA6,
		COMPONENT_KNUCKLE_VARMOD_PIMP = 0xC613F685,
		COMPONENT_KNUCKLE_VARMOD_PLAYER = 0x8B808BB,
		COMPONENT_KNUCKLE_VARMOD_VAGOS = 0x7AF3F785,

		// Enhanced edition: None

		// Lowriders:

		COMPONENT_MACHINEPISTOL_CLIP_01 = 0x476E85FF,
		COMPONENT_MACHINEPISTOL_CLIP_02 = 0xB92C6979,
		COMPONENT_MACHINEPISTOL_CLIP_03 = 0xA9E9CAF4,

		// Executives and Other Criminals:

		COMPONENT_SWITCHBLADE_VARMOD_BASE = 0x9137A500,
		COMPONENT_SWITCHBLADE_VARMOD_VAR1 = 0x5B3E7DB6,
		COMPONENT_SWITCHBLADE_VARMOD_VAR2 = 0xE7939662,
		COMPONENT_REVOLVER_CLIP_01 = 0xE9867CE3,
		COMPONENT_REVOLVER_VARMOD_BOSS = 0x16EE3040,
		COMPONENT_REVOLVER_VARMOD_GOON = 0x9493B80D,

		// Lowriders: Custom Classics:

		COMPONENT_COMPACTRIFLE_CLIP_01 = 0x513F0A63,
		COMPONENT_COMPACTRIFLE_CLIP_02 = 0x59FF9BF8,
		COMPONENT_COMPACTRIFLE_CLIP_03 = 0xC607740E,

		// Bikers:
		COMPONENT_MINISMG_CLIP_01 = 0x84C8B2D3,
		COMPONENT_MINISMG_CLIP_02 = 0x937ED0B7,

		// Gunrunning:
		COMPONENT_PISTOL_MK2_CLIP_01 = 0x94F42D62,
		COMPONENT_PISTOL_MK2_CLIP_02 = 0x5ED6C128,
		COMPONENT_PISTOL_MK2_CLIP_TRACER = 0x25CAAEAF,
		COMPONENT_PISTOL_MK2_CLIP_INCENDIARY = 0x2BBD7A3A,
		COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT = 0x85FEA109,
		COMPONENT_PISTOL_MK2_CLIP_FMJ = 0x4F37DF2A,
		COMPONENT_PISTOL_MK2_CAMO = 0x5C6C749C,
		COMPONENT_PISTOL_MK2_CAMO_02 = 0x15F7A390,
		COMPONENT_PISTOL_MK2_CAMO_03 = 0x968E24DB,
		COMPONENT_PISTOL_MK2_CAMO_04 = 0x17BFA99,
		COMPONENT_PISTOL_MK2_CAMO_05 = 0xF2685C72,
		COMPONENT_PISTOL_MK2_CAMO_06 = 0xDD2231E6,
		COMPONENT_PISTOL_MK2_CAMO_07 = 0xBB43EE76,
		COMPONENT_PISTOL_MK2_CAMO_08 = 0x4D901310,
		COMPONENT_PISTOL_MK2_CAMO_09 = 0x5F31B653,
		COMPONENT_PISTOL_MK2_CAMO_10 = 0x697E19A0,
		COMPONENT_PISTOL_MK2_CAMO_IND_01 = 0x930CB951,
		COMPONENT_SMG_MK2_CLIP_01 = 0x4C24806E,
		COMPONENT_SMG_MK2_CLIP_02 = 0xB9835B2E,
		COMPONENT_SMG_MK2_CLIP_TRACER = 0x7FEA36EC,
		COMPONENT_SMG_MK2_CLIP_INCENDIARY = 0xD99222E5,
		COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT = 0x3A1BD6FA,
		COMPONENT_SMG_MK2_CLIP_FMJ = 0xB5A715F,
		COMPONENT_SMG_MK2_CAMO = 0xC4979067,
		COMPONENT_SMG_MK2_CAMO_02 = 0x3815A945,
		COMPONENT_SMG_MK2_CAMO_03 = 0x4B4B4FB0,
		COMPONENT_SMG_MK2_CAMO_04 = 0xEC729200,
		COMPONENT_SMG_MK2_CAMO_05 = 0x48F64B22,
		COMPONENT_SMG_MK2_CAMO_06 = 0x35992468,
		COMPONENT_SMG_MK2_CAMO_07 = 0x24B782A5,
		COMPONENT_SMG_MK2_CAMO_08 = 0xA2E67F01,
		COMPONENT_SMG_MK2_CAMO_09 = 0x2218FD68,
		COMPONENT_SMG_MK2_CAMO_10 = 0x45C5C3C5,
		COMPONENT_SMG_MK2_CAMO_IND_01 = 0x399D558F,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_01 = 0x8610343F,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_02 = 0xD12ACA6F,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER = 0xEF2C78C1,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY = 0xFB70D853,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING = 0xA7DD1E58,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ = 0x63E0A098,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO = 0x911B24AF,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_02 = 0x37E5444B,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_03 = 0x538B7B97,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_04 = 0x25789F72,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_05 = 0xC5495F2D,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_06 = 0xCF8B73B1,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_07 = 0xA9BB2811,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_08 = 0xFC674D54,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_09 = 0x7C7FCD9B,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_10 = 0xA5C38392,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01 = 0xB9B15DB0,
		COMPONENT_CARBINERIFLE_MK2_CLIP_01 = 0x4C7A391E,
		COMPONENT_CARBINERIFLE_MK2_CLIP_02 = 0x5DD5DBD5,
		COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER = 0x1757F566,
		COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY = 0x3D25C2A7,
		COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING = 0x255D5D57,
		COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ = 0x44032F11,
		COMPONENT_CARBINERIFLE_MK2_CAMO = 0x4BDD6F16,
		COMPONENT_CARBINERIFLE_MK2_CAMO_02 = 0x406A7908,
		COMPONENT_CARBINERIFLE_MK2_CAMO_03 = 0x2F3856A4,
		COMPONENT_CARBINERIFLE_MK2_CAMO_04 = 0xE50C424D,
		COMPONENT_CARBINERIFLE_MK2_CAMO_05 = 0xD37D1F2F,
		COMPONENT_CARBINERIFLE_MK2_CAMO_06 = 0x86268483,
		COMPONENT_CARBINERIFLE_MK2_CAMO_07 = 0xF420E076,
		COMPONENT_CARBINERIFLE_MK2_CAMO_08 = 0xAAE14DF8,
		COMPONENT_CARBINERIFLE_MK2_CAMO_09 = 0x9893A95D,
		COMPONENT_CARBINERIFLE_MK2_CAMO_10 = 0x6B13CD3E,
		COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01 = 0xDA55CD3F,
		COMPONENT_COMBATMG_MK2_CLIP_01 = 0x492B257C,
		COMPONENT_COMBATMG_MK2_CLIP_02 = 0x17DF42E9,
		COMPONENT_COMBATMG_MK2_CLIP_TRACER = 0xF6649745,
		COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY = 0xC326BDBA,
		COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING = 0x29882423,
		COMPONENT_COMBATMG_MK2_CLIP_FMJ = 0x57EF1CC8,
		COMPONENT_COMBATMG_MK2_CAMO = 0x4A768CB5,
		COMPONENT_COMBATMG_MK2_CAMO_02 = 0xCCE06BBD,
		COMPONENT_COMBATMG_MK2_CAMO_03 = 0xBE94CF26,
		COMPONENT_COMBATMG_MK2_CAMO_04 = 0x7609BE11,
		COMPONENT_COMBATMG_MK2_CAMO_05 = 0x48AF6351,
		COMPONENT_COMBATMG_MK2_CAMO_06 = 0x9186750A,
		COMPONENT_COMBATMG_MK2_CAMO_07 = 0x84555AA8,
		COMPONENT_COMBATMG_MK2_CAMO_08 = 0x1B4C088B,
		COMPONENT_COMBATMG_MK2_CAMO_09 = 0xE046DFC,
		COMPONENT_COMBATMG_MK2_CAMO_10 = 0x28B536E,
		COMPONENT_COMBATMG_MK2_CAMO_IND_01 = 0xD703C94D,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_01 = 0xFA1E1A28,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_02 = 0x2CD8FF9D,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY = 0xEC0F617,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING = 0xF835D6D4,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ = 0x3BE948F6,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE = 0x89EBDAA7,
		COMPONENT_HEAVYSNIPER_MK2_CAMO = 0xF8337D02,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_02 = 0xC5BEDD65,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_03 = 0xE9712475,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_04 = 0x13AA78E7,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_05 = 0x26591E50,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_06 = 0x302731EC,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_07 = 0xAC722A78,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_08 = 0xBEA4CEDD,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_09 = 0xCD776C82,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_10 = 0xABC5ACC7,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01 = 0x6C32D2EB,
	};

	Hash weaponUpgrades[] = {
		COMPONENT_ADVANCEDRIFLE_CLIP_02,
		COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE,
		COMPONENT_APPISTOL_CLIP_02,
		COMPONENT_APPISTOL_VARMOD_LUXE,
		COMPONENT_ASSAULTRIFLE_CLIP_02,
		COMPONENT_ASSAULTRIFLE_CLIP_03,
		COMPONENT_ASSAULTRIFLE_VARMOD_LUXE,
		COMPONENT_ASSAULTSHOTGUN_CLIP_02,
		COMPONENT_ASSAULTSMG_CLIP_02,
		COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER,
		COMPONENT_AT_AR_AFGRIP,
		COMPONENT_AT_AR_FLSH,
		COMPONENT_AT_AR_SUPP,
		COMPONENT_AT_AR_SUPP_02,
		COMPONENT_AT_PI_FLSH,
		COMPONENT_AT_PI_SUPP,
		COMPONENT_AT_PI_SUPP_02,
		COMPONENT_AT_RAILCOVER_01,
		COMPONENT_AT_SCOPE_LARGE,
		COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM,
		COMPONENT_AT_SCOPE_MACRO,
		COMPONENT_AT_SCOPE_MACRO_02,
		COMPONENT_AT_SCOPE_MAX,
		COMPONENT_AT_SCOPE_MEDIUM,
		COMPONENT_AT_SCOPE_SMALL,
		COMPONENT_AT_SCOPE_SMALL_02,
		COMPONENT_AT_SR_SUPP,
		COMPONENT_AT_SCOPE_LARGE_MK2,
		COMPONENT_AT_SCOPE_NV,
		COMPONENT_AT_SCOPE_THERMAL,
		COMPONENT_AT_SR_SUPP_03,
		COMPONENT_AT_SR_BARREL_01,
		COMPONENT_AT_SR_BARREL_02,
		COMPONENT_AT_SCOPE_SMALL_MK2,
		COMPONENT_AT_MG_BARREL_01,
		COMPONENT_AT_MG_BARREL_02,
		COMPONENT_AT_SIGHTS_SMG,
		COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2,
		COMPONENT_AT_SCOPE_SMALL_SMG_MK2,
		COMPONENT_AT_MUZZLE_01,
		COMPONENT_AT_MUZZLE_02,
		COMPONENT_AT_MUZZLE_03,
		COMPONENT_AT_MUZZLE_04,
		COMPONENT_AT_MUZZLE_05,
		COMPONENT_AT_MUZZLE_06,
		COMPONENT_AT_MUZZLE_07,
		COMPONENT_AT_MUZZLE_08,
		COMPONENT_AT_MUZZLE_09,
		COMPONENT_AT_SB_BARREL_01,
		COMPONENT_AT_SB_BARREL_02,
		COMPONENT_AT_PI_RAIL,
		COMPONENT_AT_PI_FLSH_02,
		COMPONENT_AT_PI_COMP,
		COMPONENT_AT_AR_AFGRIP_02,
		COMPONENT_AT_SIGHTS,
		COMPONENT_AT_SCOPE_MACRO_MK2,
		COMPONENT_AT_SCOPE_MEDIUM_MK2,
		COMPONENT_AT_AR_BARREL_01,
		COMPONENT_AT_AR_BARREL_02,
		COMPONENT_AT_CR_BARREL_01,
		COMPONENT_AT_CR_BARREL_02,
		COMPONENT_CARBINERIFLE_CLIP_02,
		COMPONENT_CARBINERIFLE_CLIP_03,
		COMPONENT_CARBINERIFLE_VARMOD_LUXE,
		COMPONENT_COMBATMG_CLIP_02,
		COMPONENT_COMBATMG_VARMOD_LOWRIDER,
		COMPONENT_COMBATPISTOL_CLIP_02,
		COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER,
		COMPONENT_MG_CLIP_02,
		COMPONENT_MG_VARMOD_LOWRIDER,
		COMPONENT_MICROSMG_CLIP_02,
		COMPONENT_MICROSMG_VARMOD_LUXE,
		COMPONENT_PISTOL50_CLIP_02,
		COMPONENT_PISTOL50_VARMOD_LUXE,
		COMPONENT_PISTOL_CLIP_02,
		COMPONENT_PISTOL_VARMOD_LUXE,
		COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER,
		COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE,
		COMPONENT_SMG_CLIP_02,
		COMPONENT_SMG_CLIP_03,
		COMPONENT_SMG_VARMOD_LUXE,
		COMPONENT_SNIPERRIFLE_VARMOD_LUXE,

		// DLC
		COMPONENT_SNSPISTOL_CLIP_02,
		COMPONENT_SNSPISTOL_VARMOD_LOWRIDER,
		COMPONENT_GUSENBERG_CLIP_02,
		COMPONENT_SPECIALCARBINE_CLIP_02,
		COMPONENT_SPECIALCARBINE_CLIP_03,
		COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER,
		COMPONENT_HEAVYPISTOL_CLIP_02,
		COMPONENT_HEAVYPISTOL_VARMOD_LUXE,
		COMPONENT_BULLPUPRIFLE_CLIP_02,
		COMPONENT_BULLPUPRIFLE_VARMOD_LOW,
		COMPONENT_VINTAGEPISTOL_CLIP_02,
		COMPONENT_HEAVYSHOTGUN_CLIP_02,
		COMPONENT_HEAVYSHOTGUN_CLIP_03,
		COMPONENT_MARKSMANRIFLE_CLIP_02,
		COMPONENT_MARKSMANRIFLE_VARMOD_LUXE,
		COMPONENT_COMBATPDW_CLIP_02,
		COMPONENT_COMBATPDW_CLIP_03,
		COMPONENT_KNUCKLE_VARMOD_VAGOS,
		COMPONENT_MACHINEPISTOL_CLIP_02,
		COMPONENT_MACHINEPISTOL_CLIP_03,
		COMPONENT_SWITCHBLADE_VARMOD_BASE,
		COMPONENT_SWITCHBLADE_VARMOD_VAR1,
		COMPONENT_SWITCHBLADE_VARMOD_VAR2,
		COMPONENT_REVOLVER_VARMOD_BOSS,
		COMPONENT_COMPACTRIFLE_CLIP_02,
		COMPONENT_COMPACTRIFLE_CLIP_03,
		COMPONENT_MINISMG_CLIP_01,
		COMPONENT_MINISMG_CLIP_02,
		COMPONENT_PISTOL_MK2_CLIP_01,
		COMPONENT_PISTOL_MK2_CLIP_02,
		COMPONENT_PISTOL_MK2_CLIP_TRACER,
		COMPONENT_PISTOL_MK2_CLIP_INCENDIARY,
		COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT,
		COMPONENT_PISTOL_MK2_CLIP_FMJ,
		COMPONENT_PISTOL_MK2_CAMO,
		COMPONENT_PISTOL_MK2_CAMO_02,
		COMPONENT_PISTOL_MK2_CAMO_03,
		COMPONENT_PISTOL_MK2_CAMO_04,
		COMPONENT_PISTOL_MK2_CAMO_05,
		COMPONENT_PISTOL_MK2_CAMO_06,
		COMPONENT_PISTOL_MK2_CAMO_07,
		COMPONENT_PISTOL_MK2_CAMO_08,
		COMPONENT_PISTOL_MK2_CAMO_09,
		COMPONENT_PISTOL_MK2_CAMO_10,
		COMPONENT_PISTOL_MK2_CAMO_IND_01,
		COMPONENT_SMG_MK2_CLIP_01,
		COMPONENT_SMG_MK2_CLIP_02,
		COMPONENT_SMG_MK2_CLIP_TRACER,
		COMPONENT_SMG_MK2_CLIP_INCENDIARY,
		COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT,
		COMPONENT_SMG_MK2_CLIP_FMJ,
		COMPONENT_SMG_MK2_CAMO,
		COMPONENT_SMG_MK2_CAMO_02,
		COMPONENT_SMG_MK2_CAMO_03,
		COMPONENT_SMG_MK2_CAMO_04,
		COMPONENT_SMG_MK2_CAMO_05,
		COMPONENT_SMG_MK2_CAMO_06,
		COMPONENT_SMG_MK2_CAMO_07,
		COMPONENT_SMG_MK2_CAMO_08,
		COMPONENT_SMG_MK2_CAMO_09,
		COMPONENT_SMG_MK2_CAMO_10,
		COMPONENT_SMG_MK2_CAMO_IND_01,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_01,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_02,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING,
		COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_02,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_03,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_04,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_05,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_06,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_07,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_08,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_09,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_10,
		COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01,
		COMPONENT_CARBINERIFLE_MK2_CLIP_01,
		COMPONENT_CARBINERIFLE_MK2_CLIP_02,
		COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER,
		COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY,
		COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING,
		COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ,
		COMPONENT_CARBINERIFLE_MK2_CAMO,
		COMPONENT_CARBINERIFLE_MK2_CAMO_02,
		COMPONENT_CARBINERIFLE_MK2_CAMO_03,
		COMPONENT_CARBINERIFLE_MK2_CAMO_04,
		COMPONENT_CARBINERIFLE_MK2_CAMO_05,
		COMPONENT_CARBINERIFLE_MK2_CAMO_06,
		COMPONENT_CARBINERIFLE_MK2_CAMO_07,
		COMPONENT_CARBINERIFLE_MK2_CAMO_08,
		COMPONENT_CARBINERIFLE_MK2_CAMO_09,
		COMPONENT_CARBINERIFLE_MK2_CAMO_10,
		COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01,
		COMPONENT_COMBATMG_MK2_CLIP_01,
		COMPONENT_COMBATMG_MK2_CLIP_02,
		COMPONENT_COMBATMG_MK2_CLIP_TRACER,
		COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY,
		COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING,
		COMPONENT_COMBATMG_MK2_CLIP_FMJ,
		COMPONENT_COMBATMG_MK2_CAMO,
		COMPONENT_COMBATMG_MK2_CAMO_02,
		COMPONENT_COMBATMG_MK2_CAMO_03,
		COMPONENT_COMBATMG_MK2_CAMO_04,
		COMPONENT_COMBATMG_MK2_CAMO_05,
		COMPONENT_COMBATMG_MK2_CAMO_06,
		COMPONENT_COMBATMG_MK2_CAMO_07,
		COMPONENT_COMBATMG_MK2_CAMO_08,
		COMPONENT_COMBATMG_MK2_CAMO_09,
		COMPONENT_COMBATMG_MK2_CAMO_10,
		COMPONENT_COMBATMG_MK2_CAMO_IND_01,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_01,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_02,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ,
		COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE,
		COMPONENT_HEAVYSNIPER_MK2_CAMO,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_02,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_03,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_04,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_05,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_06,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_07,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_08,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_09,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_10,
		COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01,
	};

	Hash usableWeaponHashes[87] = {
		126349499,
		2694266206,
		1233104067,
		101631238,
		911657153,
		1834241177,
		0x1B06D571,
		0x5EF9FEC4,
		0x22D8FE39,
		0x99AEEB3B,
		0x2BE6766B,
		0x13532244,
		0xBFEFFF6D,
		0x83BF0278,
		0xAF113F99,
		0x9D07F764,
		0x7FD62962,
		0x1D073A89,
		0x7846A318,
		0xE284C527,
		0xC472FE2,
		0x5FC3C11,
		0xA284510B,
		0xB1CA77B1,
		0x42BF8A85,
		0x93E220BD,
		0xFDBC8A50,
		0x2C3731D9,
		0x24B17070,
		0x34A67B97,
		0xFBAB5776,
		0x99B507EA,
		0x678B81B1,
		0x4E875F73,
		0x958A4A8F,
		0x84BD7BFD,
		0x440E4788,
		0xEFE7E2DF,
		0x9D61E50F,
		0xF9E6AA4B,
		0xC0A3098D,
		0xBFD21232,
		0x476BF155,
		0xAF3696A1,
		0xB62D1F67,
		0xD205520E,
		0x7F229F94,
		0x61012683,
		0x83839C4,
		0x92A27487,
		0xA89CB99E,
		0x7F7497E5,
		0x47757124,
		0x3AABBBAA,
		0xC734385A,
		0xAB564B93,
		0x63AB0442,
		0xF9DCBF2D,
		0xA3D4D34,
		0xD8DF3C3C,
		0xDC4DB296,
		0xDD5DF8D9,
		0xDB1AA450,
		0xEF951FBB,
		0x624FE830,
		0x8BB05FD7,
		0xC1B3C3D1,
		0xDFE37640,
		0x78A97CD0,
		0xA914799,
		0x394F415C,
		0x19044EE0,
		0x781FE4A,
		0x12E82D3D,
		0x176898A6,
		0x787F0BB,
		0xE232C28C,
		0xD04C944D,
		0x0A3D4D34,
		0x6D544C99,
		0x2C082D7D,
		0xCD274149,
		0xBD248B55,
		0xBA45E8B8,
		0x94117305,
		0x060EC506,
		0xFDBADCED
	};

	static struct Weapon {
		char* hash;
		char* name;
		char* icon;
		vector<uint> componentHashes;
		vector<char*> componentNames;
		vector<char*> statHashes;
		vector<char*> statNames;
		char* heldTime;
	} Weapons[] = {
		//Melee
		{ "WEAPON_UNARMED", "Unarmed", "weapon_unarmed",{},{},
	{ "UNARMED_KILLS", "UNARMED_HITS" },
	{ "Kills", "Hits" } },

	{ "WEAPON_KNUCKLE", "Knuckledusters", "weapon_knuckle",{},{},
	{ "KNUCKLE_KILLS", "KNUCKLE_HITS" },
	{ "Kills", "Hits" }, "KNUCKLE_HELDTIME" },

	{ "WEAPON_MACHETE", "Machette", "weapon_machete",{},{},
	{ "MACHETE_KILLS", "MACHETE_HITS" },
	{ "Kills", "Hits" }, "MACHETE_HELDTIME" },

	{ "WEAPON_KNIFE", "Knife", "weapon_knife",{},{},
	{ "KNIFE_KILLS", "KNIFE_HITS" },
	{ "Kills", "Hits" }, "KNIFE_HELDTIME" },

	{ "WEAPON_SWITCHBLADE", "Switch Blade", "weapon_switchblade",{},{},
	{ "SWBLADE_KILLS", "SWBLADE_HITS" },
	{ "Kills", "Hits" }, "SWBLADE_HELDTIME" },

	{ "WEAPON_DAGGER", "Dagger", "weapon_dagger",{},{},
	{ "DAGGER_KILLS", "DAGGER_HITS" },
	{ "Kills", "Hits" }, "DAGGER_HELDTIME" },

	{ "WEAPON_BOTTLE", "Bottle", "weapon_bottle",{},{},
	{ "BOTTLE_KILLS", "BOTTLE_HITS" },
	{ "Kills", "Hits" }, "BOTTLE_HELDTIME" },

	{ "WEAPON_WRENCH", "Wrench", "weapon_wrench",{},{},
	{ "WRENCH_KILLS", "WRENCH_HITS" },
	{ "Kills", "Hits" }, "WRENCH_HELDTIME" },

	{ "WEAPON_HAMMER", "Hammer", "weapon_hammer",{},{},
	{ "HAMMER_KILLS", "HAMMER_HITS" },
	{ "Kills", "Hits" }, "HAMMER_HELDTIME" },

	{ "WEAPON_HATCHET", "Hatchet", "weapon_hatchet",{},{},
	{ "HATCHET_KILLS", "HATCHET_HITS" },
	{ "Kills", "Hits" }, "HATCHET_HELDTIME" },

	{ "WEAPON_BATTLEAXE", "Battle Axe", "weapon_battle_axe",{},{},
	{ "BATTLEAXE_KILLS", "BATTLEAXE_HITS" },
	{ "Kills", "Hits" }, "BATTLEAXE_HELDTIME" },

	{ "WEAPON_CROWBAR", "Crowbar", "weapon_crowbar",{},{},
	{ "CROWBAR_KILLS", "CROWBAR_HITS" },
	{ "Kills", "Hits" }, "CROWBAR_HELDTIME" },

	{ "WEAPON_NIGHTSTICK", "Nightstick", "weapon_nightstick",{},{},
	{ "NIGHTSTICK_KILLS", "NIGHTSTICK_HITS" },
	{ "Kills", "Hits" }, "NIGHTSTICK_HELDTIME" },

	{ "WEAPON_BAT", "Baseball Bat", "weapon_bat",{},{},
	{ "BAT_KILLS", "BAT_HITS" },
	{ "Kills", "Hits" }, "BAT_HELDTIME" },

	{ "WEAPON_GOLFCLUB", "Golf Club", "weapon_golfclub",{},{},
	{ "GCLUB_KILLS", "GCLUB_HITS" },
	{ "Kills", "Hits" }, "GCLUB_HELDTIME" },

	{ "WEAPON_POOLCUE", "Pool Cue", "weapon_pool_cue",{},{},
	{ "POOLCUE_KILLS", "POOLCUE_HITS" },
	{ "Kills", "Hits" }, "POOLCUE_HELDTIME" },

	{ "WEAPON_FLASHLIGHT", "Flashlight", "weapon_flashlight",{},{},
	{ "FLASHLIGHT_KILLS", "FLASHLIGHT_HITS" },
	{ "Kills", "Hits" }, "FLASHLIGHT_HELDTIME" },
	//17

	//Pistols
	{ "WEAPON_PISTOL", "Pistol", "weapon_pistol",{ 0xED265A1C, 0x359B7AAE, 0x65EA7EBB, 0xD7391086 },{ "Extended clip", "Flashlight", "Suppressor", "Special finish" },
	{ "PISTOL_KILLS", "PISTOL_SHOTS", "PISTOL_HITS", "PISTOL_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "PISTOL_HELDTIME" },

	{ "WEAPON_REVOLVER", "Revolver", "weapon_revolver",{},{},
	{ "REVOLVER_KILLS", "REVOLVER_SHOTS", "REVOLVER_HITS", "REVOLVER_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "REVOLVER_HELDTIME" },

	{ "WEAPON_COMBATPISTOL", "Combat Pistol", "weapon_pistol_combat",{ 0xD67B4F2D, 0x359B7AAE, 0xC304849A },{ "Extended clip", "Flashlight", "Suppressor" },
	{ "CMBTPISTOL_KILLS", "CMBTPISTOL_SHOTS", "CMBTPISTOL_HITS", "CMBTPISTOL_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "CMBTPISTOL_HELDTIME" },

	{ "WEAPON_PISTOL50", "Pistol .50", "weapon_pistol_50",{ 0xD9D3AC92, 0x359B7AAE, 0xA73D4664, 0x77B8AB2F },{ "Extended clip", "Flashlight", "Suppressor", "Special finish" },
	{ "PISTOL50_KILLS", "PISTOL50_SHOTS", "PISTOL50_HITS", "PISTOL50_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "PISTOL50_HELDTIME" },

	{ "WEAPON_SNSPISTOL", "SNS Pistol", "weapon_snspistol",{ 0x7B0033B3, 0xF8802ED9 },{ "Extended clip", "Regular clip" },
	{ "SNSPISTOL_KILLS", "SNSPISTOL_SHOTS", "SNSPISTOL_HITS", "SNSPISTOL_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "SNSPISTOL_HELDTIME" },

	{ "WEAPON_APPISTOL", "AP Pistol", "weapon_pistol_ap",{ 0x249A17D5, 0x359B7AAE, 0xC304849A, 0x9B76C72C },{ "Extended clip", "Flashlight", "Suppressor", "Special finish" },
	{ "APPISTOL_KILLS", "APPISTOL_SHOTS", "APPISTOL_HITS", "APPISTOL_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "APPISTOL_HELDTIME" },

	{ "WEAPON_HEAVYPISTOL", "Heavy Pistol", "weapon_heavypistol",{ 0x64F9C62B, 0xD4A969A, 0x359B7AAE, 0xC304849A, 0x7A6A7B7B },{ "Extended clip", "Regular clip", "Flashlight", "Suppressor", "Special finish" },{},{} },
	{ "WEAPON_MARKSMANPISTOL", "Marksman Pistol", "weapon_marksmanpistol",{},{},
	{ "MKPISTOL_KILLS", "MKPISTOL_SHOTS", "MKPISTOL_HITS", "MKPISTOL_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "MKPISTOL_HELDTIME" },

	{ "WEAPON_VINTAGEPISTOL", "Vintage Pistol", "weapon_vintagepistol",{ 0x33BA12E8, 0xC304849A },{ "Extended clip", "Suppressor" },{},{} },
	{ "WEAPON_STUNGUN", "Stun Gun", "weapon_stungun",{},{},
	{ "STUNGUN_KILLS", "STUNGUN_SHOTS", "STUNGUN_HITS", "STUNGUN_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "STUNGUN_HELDTIME" },

	{ "WEAPON_FLAREGUN", "Flare Gun", "weapon_flare_gun",{},{},
	{ "FLAREGUN_KILLS", "FLAREGUN_SHOTS", "FLAREGUN_HITS", "FLAREGUN_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "FLAREGUN_HELDTIME" },
	//28

	//Submachine guns
	{ "WEAPON_MACHINEPISTOL", "Machine Pistol", "weapon_machinepistol",{},{},
	{ "MCHPIST_KILLS", "MCHPIST_SHOTS", "MCHPIST_HITS", "MCHPIST_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "MCHPIST_HELDTIME" },

	{ "WEAPON_MICROSMG", "Micro SMG", "weapon_smg_micro",{ 0x10E6BA2B, 0x359B7AAE, 0x9D2FBF29, 0xA73D4664, 0x487AAE09 },{ "Extended clip", "Flashlight", "Scope", "Suppressor", "Special finish" },
	{ "MICROSMG_KILLS", "MICROSMG_SHOTS", "MICROSMG_HITS", "MICROSMG_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "MICROSMG_HELDTIME" },

	{ "WEAPON_MINISMG", "Mini SMG", "weapon_mini_smg",{},{},
	{ "MINISMG_KILLS", "MINISMG_SHOTS", "MINISMG_HITS", "MINISMG_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "MINISMG_HELDTIME" },

	{ "WEAPON_SMG", "SMG", "weapon_smg",{ 0x350966FB, 0x7BC4CDDC, 0x3CC6BA57, 0xC304849A, 0x27872C90 },{ "Extended clip", "Flashlight", "Scope", "Suppressor", "Special finish" },
	{ "SMG_KILLS", "SMG_SHOTS", "SMG_HITS", "SMG_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "SMG_HELDTIME" },

	{ "WEAPON_ASSAULTSMG", "Assault SMG", "weapon_smg_assault",{ 0xBB46E417, 0x7BC4CDDC, 0x9D2FBF29, 0xA73D4664 },{ "Extended clip", "Flashlight", "Scope", "Suppressor" },
	{ "ASLTSMG_KILLS", "ASLTSMG_SHOTS", "ASLTSMG_HITS", "ASLTSMG_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "ASLTSMG_HELDTIME" },

	{ "WEAPON_COMBATPDW", "Combat PDW", "weapon_combatpdw",{ 0x334A5203, 0x7BC4CDDC, 0xC164F53, 0xAA2C45B4 },{ "Extended clip", "Flashlight", "Grip", "Scope" },
	{ "COMBATPDW_KILLS", "COMBATPDW_SHOTS", "COMBATPDW_HITS", "COMBATPDW_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "COMBATPDW_HELDTIME" },

	//Assault rifles
	{ "WEAPON_ASSAULTRIFLE", "Assault Rifle", "weapon_rifle_assault",{ 0xB1214F9B, 0x7BC4CDDC, 0xC164F53, 0x9D2FBF29, 0xA73D4664, 0x4EAD7533 },{ "Extended clip", "Flashlight", "Grip", "Scope", "Suppressor", "Special finish" },
	{ "ASLTRIFLE_KILLS", "ASLTRIFLE_SHOTS", "ASLTRIFLE_HITS", "ASLTRIFLE_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "ASLTRIFLE_HELDTIME" },

	{ "WEAPON_CARBINERIFLE", "Carbine Rifle", "weapon_rifle_carbine",{ 0x91109691, 0x7BC4CDDC, 0xC164F53, 0xA0D89C42, 0x837445AA, 0xD89B9658 },{ "Extended clip", "Flashlight", "Grip", "Scope", "Suppressor", "Special finish" },
	{ "CRBNRIFLE_KILLS", "CRBNRIFLE_SHOTS", "CRBNRIFLE_HITS", "CRBNRIFLE_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "CRBNRIFLE_HELDTIME" },

	{ "WEAPON_ADVANCEDRIFLE", "Advanced Rifle", "weapon_rifle_advanced",{ 0x8EC1C979, 0x7BC4CDDC, 0xAA2C45B4, 0x837445AA, 0x377CD377 },{ "Extended clip", "Flashlight", "Scope", "Suppressor", "Special finish" },
	{ "ADVRIFLE_KILLS", "ADVRIFLE_SHOTS", "ADVRIFLE_HITS", "ADVRIFLE_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "ADVRIFLE_HELDTIME" },

	{ "WEAPON_BULLPUPRIFLE", "Bullpup Rifle", "weapon_bullpuprifle",{ 0xB3688B0F, 0xC5A12F80, 0x7BC4CDDC, 0xC164F53, 0xAA2C45B4, 0x837445AA },{ "Extended clip", "Regular clip", "Flashlight", "Grip", "Scope", "Suppressor" },{},{} },
	{ "WEAPON_COMPACTRIFLE", "Compact Rifle", "weapon_compactrifle",{},{},
	{ "CMPRIFLE_KILLS", "CMPRIFLE_SHOTS", "CMPRIFLE_HITS", "CMPRIFLE_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "CMPRIFLE_HELDTIME" },

	{ "WEAPON_SPECIALCARBINE", "Special Carbine", "weapon_specialcarbine",{ 0x7C8BD10E, 0xC6C7E581, 0x7BC4CDDC, 0xC164F53, 0xA0D89C42, 0xA73D4664 },{ "Extended clip", "Regular clip", "Flashlight", "Grip", "Scope", "Suppressor" },{},{} },

	//LMGs
	{ "WEAPON_MG", "MG", "weapon_lmg",{ 0x82158B47, 0x3C00AFED },{ "Extended clip", "Scope" },
	{ "MG_KILLS", "MG_SHOTS", "MG_HITS", "MG_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "MG_HELDTIME" },

	{ "WEAPON_COMBATMG", "Combat MG", "weapon_lmg_combat",{ 0xD6C59CD6, 0xE1FFB34A, 0xC164F53, 0xA0D89C42 },{ "Extended clip", "Regular clip", "Grip", "Scope" },
	{ "CMBTMG_KILLS", "CMBTMG_SHOTS", "CMBTMG_HITS", "CMBTMG_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "CMBTMG_HELDTIME" },

	{ "WEAPON_GUSENBERG", "Gusenberg Sweeper", "weapon_gusenberg",{ 0xEAC8C270 },{ "Extended clip" },{},{} },

	//Shotguns
	{ "WEAPON_SAWNOFFSHOTGUN", "Sawed-Off Shotgun", "weapon_shotgun_sawnoff",{ 0x85A64DF9 },{ "Special finish" },
	{ "SAWNOFF_KILLS", "SAWNOFF_SHOTS", "SAWNOFF_HITS", "SAWNOFF_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "SAWNOFF_HELDTIME" },

	{ "WEAPON_PUMPSHOTGUN", "Pump Shotgun", "weapon_shotgun_pump",{ 0x7BC4CDDC, 0xE608B35E },{ "Flashlight", "Suppressor" },
	{ "PUMP_KILLS", "PUMP_SHOTS", "PUMP_HITS", "PUMP_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "PUMP_HELDTIME" },

	{ "WEAPON_ASSAULTSHOTGUN", "Assault Shotgun", "weapon_shotgun_assault",{ 0x86BD7F72, 0x7BC4CDDC, 0xC164F53, 0x837445AA },{ "Extended clip", "Flashlight", "Grip", "Suppressor" },
	{ "ASLTSHTGN_KILLS", "ASLTSHTGN_SHOTS", "ASLTSHTGN_HITS", "ASLTSHTGN_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "ASLTSHTGN_HELDTIME" },

	{ "WEAPON_BULLPUPSHOTGUN", "Bullpup Shotgun", "weapon_shotgun_bullpup",{ 0x7BC4CDDC, 0xC164F53, 0xA73D4664 },{ "Flashlight", "Grip", "Suppressor" },
	{ "BULLPUP_KILLS", "BULLPUP_SHOTS", "BULLPUP_HITS", "BULLPUP_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "BULLPUP_HELDTIME" },

	{ "WEAPON_DBSHOTGUN", "Double Barrel Shotgun", "weapon_dbshotgun",{},{},
	{ "DBSHGN_KILLS", "DBSHGN_SHOTS", "DBSHGN_HITS", "DBSHGN_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "DBSHGN_HELDTIME" },


	{ "WEAPON_HEAVYSHOTGUN", "Heavy Shotgun", "weapon_heavyshotgun",{ 0x971CF6FD, 0x971CF6FD, 0xC164F53, 0xA73D4664 },{ "Extended clip", "Flashlight", "Grip", "Suppressor" },{},{} },
	{ "WEAPON_MUSKET", "Musket", "weapon_musket",{},{},
	{ "MUSKET_KILLS", "MUSKET_SHOTS", "MUSKET_HITS", "MUSKET_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "MUSKET_HELDTIME" },

	{ "WEAPON_AUTOSHOTGUN", "Sweeper Shotgun", "weapon_automatic_shotgun",{},{},
	{ "AUTOSHGN_KILLS", "AUTOSHGN_SHOTS", "AUTOSHGN_HITS", "AUTOSHGN_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "AUTOSHGN_HELDTIME" },

	//Sniper rifles
	{ "WEAPON_SNIPERRIFLE", "Sniper Rifle", "weapon_sniper",{ 0xBC54DA77, 0xD2443DDC, 0xA73D4664, 0x4032B5E7, 0x9BC64089 },{ "Advanced scope", "Scope", "Suppressor", "Special finish", "???" },
	{ "SNIPERRFL_KILLS", "SNIPERRFL_SHOTS", "SNIPERRFL_HITS", "SNIPERRFL_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "SNIPERRFL_HELDTIME" },

	{ "WEAPON_MARKSMANRIFLE", "Marksman Rifle", "weapon_marksmanrifle",{},{},{},{} },
	{ "WEAPON_HEAVYSNIPER", "Heavy Sniper", "weapon_sniper_heavy",{ 0xBC54DA77, 0xD2443DDC },{ "Advanced scope", "Scope" },
	{ "HVYSNIPER_KILLS", "HVYSNIPER_SHOTS", "HVYSNIPER_HITS", "HVYSNIPER_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "HVYSNIPER_HELDTIME" },


	//Heavy
	{ "WEAPON_FIREWORK", "Firework Launcher", "weapon_firework",{},{},
	{ "FIREWRK_KILLS", "FIREWRK_SHOTS", "FIREWRK_HITS", "FIREWRK_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "FIREWRK_HELDTIME" },

	{ "WEAPON_COMPACTLAUNCHER", "Compact Grenade Launcher", "weapon_compact_grenade_launcher",{},{},
	{ "CMPGL_KILLS", "CMPGL_SHOTS", "CMPGL_HITS", "CMPGL_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "CMPGL_HELDTIME" },

	{ "WEAPON_GRENADELAUNCHER", "Grenade Launcher", "weapon_heavy_grenade_launcher",{},{},
	{ "GRNLAUNCH_KILLS", "GRNLAUNCH_SHOTS" },
	{ "Kills", "Shots" }, "GRNLAUNCH_HELDTIME" },

	{ "WEAPON_HOMINGLAUNCHER", "Homing Launcher", "weapon_hominglauncher",{},{},
	{ "HOMLNCH_KILLS", "HOMLNCH_SHOTS" },
	{ "Kills", "Shots" }, "HOMLNCH_HELDTIME" },

	{ "WEAPON_RPG", "Rocket Launcher", "weapon_heavy_rpg",{},{},
	{ "RPG_KILLS", "RPG_SHOTS" },
	{ "Kills", "Shots" }, "RPG_HELDTIME" },

	{ "WEAPON_RAILGUN", "Railgun", "weapon_railgun",{},{},
	{ "RAILGUN_KILLS", "RAILGUN_SHOTS" },
	{ "Kills", "Shots" }, "RAILGUN_HELDTIME" },

	{ "WEAPON_MINIGUN", "Minigun", "weapon_heavy_minigun",{},{},
	{ "MINIGUNS_KILLS", "MINIGUNS_SHOTS", "MINIGUNS_HITS", "MINIGUNS_HEADSHOTS" },
	{ "Kills", "Shots", "Hits", "Headshots" }, "MINIGUNS_HELDTIME" },


	//Throwables
	{ "WEAPON_BALL", "Ball", "weapon_ball",{},{},{},{} },
	{ "WEAPON_SNOWBALL", "Snowball", "weapon_snowball",{},{},{},{} },
	{ "WEAPON_SMOKEGRENADE", "Smoke Grenade", "weapon_thrown_bz_gas",{},{},
	{ "SMKGRENADE_KILLS", "SMKGRENADE_SHOTS", "SMKGRENADE_HITS" },
	{ "Kills", "Shots", "Hits" }, "SMKGRENADE_HELDTIME" },

	{ "WEAPON_BZGAS", "BZ Gas", "weapon_thrown_bz_gas",{},{},{},{} },
	{ "WEAPON_GRENADE", "Grenade", "weapon_thrown_grenade",{},{},
	{ "GRENADE_KILLS", "GRENADE_SHOTS" },
	{ "Kills", "Shots" }, "GRENADE_HELDTIME" },

	{ "WEAPON_PIPEBOMB", "Pipe Bomb", "weapon_pipebomb",{},{},
	{ "PIPEBOMB_KILLS", "PIPEBOMB_SHOTS" },
	{ "Kills", "Shots" }, "PIPEBOMB_HELDTIME" },

	{ "WEAPON_PROXMINE", "Proximity Mines", "weapon_proximine",{},{},{},{} },

	{ "WEAPON_STICKYBOMB", "Sticky Bomb", "weapon_thrown_sticky",{},{},
	{ "STKYBMB_KILLS", "STKYBMB_SHOTS" },
	{ "Kills", "Shots" }, "STKYBMB_HELDTIME" },

	{ "WEAPON_FLARE", "Flare", "weapon_flare",{},{},{},{} },
	{ "WEAPON_MOLOTOV", "Molotov Cocktail", "weapon_molotov",{},{},
	{ "MOLOTOV_KILLS", "MOLOTOV_SHOTS", "MOLOTOV_HITS" },
	{ "Kills", "Shots", "Hits" }, "MOLOTOV_HELDTIME" },

	{ "WEAPON_PETROLCAN", "Jerry Can", "weapon_jerry_can",{},{},{},{} },
	{ "WEAPON_FIREEXTINGUISHER", "Fire Extinguisher", "weapon_jerry_can",{},{},{},{} },
	//73

	//MKII
	{ "WEAPON_PISTOL_MK2", "Pistol MKII", "weapon_pistol",{
		//0x94F42D62,
		//0x5ED6C128,
		//0x25CAAEAF,
		//0x2BBD7A3A,
		//0x85FEA109,
		//0x4F37DF2A,
		//0x0,
		0x8ED4BB70,
		0x43FD595B,
		0x65EA7EBB,
		0x21E34793,
		0x0,
		0x5C6C749C,
		0x15F7A390,
		0x968E24DB,
		0x17BFA99,
		0xF2685C72,
		0xDD2231E6,
		0xBB43EE76,
		0x4D901310,
		0x5F31B653,
		0x697E19A0,
		0x930CB951
	},{
		//"Default Clip",
		//"Extended Clip",
		//"Tracer Rounds",
		//"Incendiary Rounds",
		//"Hollow Point Rounds",
		//"Full Metal Jacket Rounds",
		//"SEPERATOR",
		"Mounted Scope",
		"Flashlight",
		"Suppressor",
		"Compensator",
		"SEPERATOR",
		"Camo 1",
		"Camo 2",
		"Camo 3",
		"Camo 4",
		"Camo 5",
		"Camo 6",
		"Camo 7",
		"Camo 8",
		"Camo 9",
		"Camo 10",
		"Camo Special"
	} },

	{ "WEAPON_SMG_MK2", "SMG MKII", "weapon_smg",{
		0x94F42D62,
		0x5ED6C128,
		//0x25CAAEAF,
		//0x2BBD7A3A,
		//0x85FEA109,
		//0x4F37DF2A,
		0x0,
		0x7BC4CDDC,
		0x9FDB5652,
		0xE502AB6B,
		0x3DECC7DA,
		0xC304849A,
		0x0,
		0xB99402D4,
		0xC867A07B,
		0xDE11CBCF,
		0xEC9068CC,
		0x2E7957A,
		0x347EF8AC,
		0x4DB62ABE,
		0xD9103EE1,
		0xA564D78B,
		0x0,
		0xC4979067,
		0x3815A945,
		0x4B4B4FB0,
		0xEC729200,
		0x48F64B22,
		0x35992468,
		0x24B782A5,
		0xA2E67F01,
		0x2218FD68,
		0x45C5C3C5,
		0x399D558F
	},{
		"Default Clip",
		"Extended Clip",
		//"Tracer Rounds",
		//"Incendiary Rounds",
		//"Hollow Point Rounds",
		//"Full Metal Jacket Rounds",
		"SEPERATOR",
		"Flashlight",
		"Holographic Sight",
		"Small Scope",
		"Medium Scope",
		"Suppressor",
		"SEPERATOR",
		"Flat Muzzle Brake",
		"Tactical Muzzle Brake",
		"Fat End Muzzle Brake",
		"Precision Muzzle Brake",
		"Heavy Duty Muzzle Brake",
		"Slanted Muzzle Brake",
		"Split End Muzzle Brake",
		"Heavy Barrel 1",
		"Heavy Barrel 2",
		"SEPERATOR",
		"Camo 1",
		"Camo 2",
		"Camo 3",
		"Camo 4",
		"Camo 5",
		"Camo 6",
		"Camo 7",
		"Camo 8",
		"Camo 9",
		"Camo 10",
		"Camo Special"
	} },

	{ "WEAPON_ASSAULTRIFLE_MK2", "Assault rifle MKII", "weapon_rifle_assault",{
		0x8610343F,
		0xD12ACA6F,
		//0xEF2C78C1,
		//0xFB70D853,
		//0xA7DD1E58,
		//0x63E0A098,
		0x0,
		0x9D65907A,
		0x7BC4CDDC,
		0x420FD713,
		0x49B2945,
		0xC66B6542,
		0xA73D4664,
		0x0,
		0xB99402D4,
		0xC867A07B,
		0xDE11CBCF,
		0xEC9068CC,
		0x2E7957A,
		0x347EF8AC,
		0x4DB62ABE,
		0x43A49D26,
		0x5646C26A,
		0x0,
		0x911B24AF,
		0x37E5444B,
		0x538B7B97,
		0x25789F72,
		0xC5495F2D,
		0xCF8B73B1,
		0xA9BB2811,
		0xFC674D54,
		0x7C7FCD9B,
		0xA5C38392,
		0xB9B15DB0
	},{
		"Default Clip",
		"Extended Clip",
		//"Tracer Rounds",
		//"Incendiary Rounds",
		//"Hollow Point Rounds",
		//"Full Metal Jacket Rounds",
		"SEPERATOR",
		"Grip",
		"Flashlight",
		"Holographic Sight",
		"Small Scope",
		"Medium Scope",
		"Suppressor",
		"SEPERATOR",
		"Flat Muzzle Brake",
		"Tactical Muzzle Brake",
		"Fat End Muzzle Brake",
		"Precision Muzzle Brake",
		"Heavy Duty Muzzle Brake",
		"Slanted Muzzle Brake",
		"Split End Muzzle Brake",
		"Heavy Barrel 1",
		"Heavy Barrel 2",
		"SEPERATOR",
		"Camo 1",
		"Camo 2",
		"Camo 3",
		"Camo 4",
		"Camo 5",
		"Camo 6",
		"Camo 7",
		"Camo 8",
		"Camo 9",
		"Camo 10",
		"Camo Special"
	} },

	{ "WEAPON_CARBINERIFLE_MK2", "Carbine rifle MKII", "weapon_rifle_carbine",{
		0x4C7A391E,
		0x5DD5DBD5,
		//0x1757F566,
		//0x3D25C2A7,
		//0x255D5D57,
		//0x44032F11,
		0x0,
		0x9D65907A,
		0x7BC4CDDC,
		0x420FD713,
		0x49B2945,
		0xC66B6542,
		0x837445AA,
		0x0,
		0xB99402D4,
		0xC867A07B,
		0xDE11CBCF,
		0xEC9068CC,
		0x2E7957A,
		0x347EF8AC,
		0x4DB62ABE,
		0x833637FF,
		0x8B3C480B,
		0x0,
		0x4BDD6F16,
		0x406A7908,
		0x2F3856A4,
		0xE50C424D,
		0xD37D1F2F,
		0x86268483,
		0xF420E076,
		0xAAE14DF8,
		0x9893A95D,
		0x6B13CD3E,
		0xDA55CD3F
	},{
		"Default Clip",
		"Extended Clip",
		//"Tracer Rounds",
		//"Incendiary Rounds",
		//"Hollow Point Rounds",
		//"Full Metal Jacket Rounds",
		"SEPERATOR",
		"Grip",
		"Flashlight",
		"Holographic Sight",
		"Small Scope",
		"Medium Scope",
		"Suppressor",
		"SEPERATOR",
		"Flat Muzzle Brake",
		"Tactical Muzzle Brake",
		"Fat End Muzzle Brake",
		"Precision Muzzle Brake",
		"Heavy Duty Muzzle Brake",
		"Slanted Muzzle Brake",
		"Split End Muzzle Brake",
		"Heavy Barrel 1",
		"Heavy Barrel 2",
		"SEPERATOR",
		"Camo 1",
		"Camo 2",
		"Camo 3",
		"Camo 4",
		"Camo 5",
		"Camo 6",
		"Camo 7",
		"Camo 8",
		"Camo 9",
		"Camo 10",
		"Camo Special"
	} },

	{ "WEAPON_COMBATMG_MK2", "Combat MG MKII", "weapon_lmg_combat",{
		0x492B257C,
		0x17DF42E9,
		//0xF6649745,
		//0xC326BDBA,
		//0x29882423,
		//0x57EF1CC8,
		0x0,
		0x420FD713,
		0x3F3C8181,
		0xC66B6542,
		0x0,
		0xB99402D4,
		0xC867A07B,
		0xDE11CBCF,
		0xEC9068CC,
		0x2E7957A,
		0x347EF8AC,
		0x4DB62ABE,
		0xC34EF234,
		0xB5E2575B,
		0x0,
		0x4A768CB5,
		0xCCE06BBD,
		0xBE94CF26,
		0x7609BE11,
		0x48AF6351,
		0x9186750A,
		0x84555AA8,
		0x1B4C088B,
		0xE046DFC,
		0x28B536E,
		0xD703C94D
	},{
		"Default Clip",
		"Extended Clip",
		//"Tracer Rounds",
		//"Incendiary Rounds",
		//"Hollow Point Rounds",
		//"Full Metal Jacket Rounds",
		"SEPERATOR",
		"Holographic Sight",
		"Small Scope",
		"Medium Scope",
		"SEPERATOR",
		"Flat Muzzle Brake",
		"Tactical Muzzle Brake",
		"Fat End Muzzle Brake",
		"Precision Muzzle Brake",
		"Heavy Duty Muzzle Brake",
		"Slanted Muzzle Brake",
		"Split End Muzzle Brake",
		"Heavy Barrel 1",
		"Heavy Barrel 2",
		"SEPERATOR",
		"Camo 1",
		"Camo 2",
		"Camo 3",
		"Camo 4",
		"Camo 5",
		"Camo 6",
		"Camo 7",
		"Camo 8",
		"Camo 9",
		"Camo 10",
		"Camo Special"
	} }

		//{ "WEAPON_HEAVYSNIPER_MK2", "Heavy sniper MKII", "weapon_sniper_heavy",{
		//	0xFA1E1A28,
		//	0x2CD8FF9D,
		//	//0xEC0F617,
		//	//0xF835D6D4,
		//	//0x3BE948F6,
		//	//0x89EBDAA7,
		//	0x0,
		//	0x82C10383,
		//	0xBC54DA77,
		//	0xB68010B0,
		//	0x2E43DA41,
		//	0x0,
		//	0xAC42DF71,
		//	0x5F7DCE4D,
		//	0x6927E1A1,
		//	0x909630B7,
		//	0x108AB09E,
		//	0x0,
		//	0xF8337D02,
		//	0xC5BEDD65,
		//	0xE9712475,
		//	0x13AA78E7,
		//	0x26591E50,
		//	0x302731EC,
		//	0xAC722A78,
		//	0xBEA4CEDD,
		//	0xCD776C82,
		//	0xABC5ACC7,
		//	0x6C32D2EB
		//},{
		//	"Default Clip",
		//	"Extended Clip",
		//	//"Incendiary Rounds",
		//	//"Hollow Point Rounds",
		//	//"Full Metal Jacket Rounds",
		//	//"Explosive Rounds",
		//	"SEPERATOR",
		//	"Medium Scope",
		//	"Large Scope",
		//	"Night Vision Scope",
		//	"Thermal Scope",
		//	"SEPERATOR",
		//	"Supressor",
		//	"Muzzle 1",
		//	"Muzzle 2",
		//	"Heavy Barrel 1",
		//	"Heavy Barrel 2",
		//	"SEPERATOR",
		//	"Camo 1",
		//	"Camo 2",
		//	"Camo 3",
		//	"Camo 4",
		//	"Camo 5",
		//	"Camo 6",
		//	"Camo 7",
		//	"Camo 8",
		//	"Camo 9",
		//	"Camo 10",
		//	"Camo Special"
		//} }
		//78
	};

	void giveallweaponeverysesh() {
		int Ammo = -1;
		for (int i = 0; i < 87; i++) {
			WEAPON::GetMaxAmmo(GetLocalPlayer().m_ped, usableWeaponHashes[i], &Ammo);
			WEAPON::GiveWeaponToPed(GetLocalPlayer().m_ped, usableWeaponHashes[i], Ammo, false, true);
		}
	}

	void giveWeapon(char* hash) {
		if (!WEAPON::HasPedGotWeapon(GetLocalPlayer().m_ped, Utils::GetHashKey(hash), 0))
		{
			WEAPON::GiveDelayedWeaponToPed(GetLocalPlayer().m_ped, Utils::GetHashKey(hash), 9999, 1);
		}
		else {
			WEAPON::SetCurrentPedWeapon(GetLocalPlayer().m_ped, Utils::GetHashKey(hash), 1);
		}
	}

	void RainbowCamo() {
		if (GetLocalPlayer().m_hasWeaponInHand) {
			static int TIMER;
			Utils::DoTimedFunction(&TIMER, 1000, [] {
				WEAPON::SetPedWeaponTintIndex(GetLocalPlayer().m_ped, GetLocalPlayer().m_weaponHash, MISC::GetRandomIntInRange(0, 7));
			});
		}
	}

}

void WeaponWeaponsMenu::Init() {
	setParentSubmenu<WeaponMenu>();
	setName("Weapons", true, true);

	addOption(ButtonOption("Get all weapons")
		.addFunction([] {
		int Ammo = -1;
		for (int i = 0; i < 87; i++) {
			WEAPON::GetMaxAmmo(GetLocalPlayer().m_ped, usableWeaponHashes[i], &Ammo);
			WEAPON::GiveWeaponToPed(GetLocalPlayer().m_ped, usableWeaponHashes[i], Ammo, false, true);
		}
	}).addTranslation().addHotkey()
		.addTooltip("Get all weapons"));

	addOption(ToggleOption("Get all weapons every session")
		.addToggle(vars.giveallweaponsloop)
		.addTranslation().addHotkey().canBeSaved()
		.addTooltip("This will give you all weapons on session load"));

	addOption(ButtonOption("Clear all weapons")
		.addFunction([] { WEAPON::RemoveAllPedWeapons(GetLocalPlayer().m_ped, true); })
		.addTooltip("Clear your inventory").addTranslation().addHotkey());

	addOption(BreakOption("Upgrades").addTranslation());

	addOption(ButtonOption("Upgrades (current weapon)")
		.addFunction([] {
		if (GetLocalPlayer().m_hasWeaponInHand) {
			for (int Component = 0; Component < 210; Component++) {
				if (WEAPON::DoesWeaponTakeWeaponComponent(GetLocalPlayer().m_weaponHash, weaponUpgrades[Component])) {
					WEAPON::GiveWeaponComponentToPed(GetLocalPlayer().m_ped, GetLocalPlayer().m_weaponHash, weaponUpgrades[Component]);
				}
			}
		}
	}).addTranslation().addHotkey()
		.addTooltip("Upgrade your current weapon"));

	addOption(ButtonOption("Upgrades (all weapons)")
		.addFunction([] {
		for (int i = 0; i < NUMOF(usableWeaponHashes) - 1; i++) {
			if (WEAPON::HasPedGotWeapon(GetLocalPlayer().m_ped, usableWeaponHashes[i], false)) {
				for (int Component = 0; Component < 210; Component++) {
					if (WEAPON::DoesWeaponTakeWeaponComponent(usableWeaponHashes[i], weaponUpgrades[Component])) {
						WEAPON::GiveWeaponComponentToPed(GetLocalPlayer().m_ped, usableWeaponHashes[i], weaponUpgrades[Component]);
					}
				}
			}
		}
	}).addTranslation().addHotkey()
		.addTooltip("Upgrade your current weapon"));

	addOption(BreakOption("Color Edits").addTranslation());

	addOption(ScrollOption<int>(SCROLL, "Camo (current weapon)")
		.addScroll(vars.camo, 0, NUMOF(camoScrollStruct) - 1, camoScrollStruct)
		.addFunction([] { WEAPON::SetPedWeaponTintIndex(GetLocalPlayer().m_ped, GetLocalPlayer().m_weaponHash, vars.camo); })
		.addTooltip("Set the camo of your current weapon").addTranslation().addHotkey());

	addOption(ScrollOption<int>(SCROLL, "Camo (all weapons)")
		.addScroll(vars.camoAll, 0, NUMOF(camoScrollStruct) - 1, camoScrollStruct)
		.addFunction([] { 
			for (int i = 0; i < NUMOF(usableWeaponHashes) - 1; i++) {
				WEAPON::SetPedWeaponTintIndex(GetLocalPlayer().m_ped, usableWeaponHashes[i], vars.camoAll);
			}
		}).addTranslation().addHotkey()
		.addTooltip("Set all weapons camo"));

	addOption(ToggleOption("Rainbow Camo (current weapon)")
		.addToggle(vars.rainbowCamo)
		.addTooltip("Spam rainbow camo").addTranslation().addHotkey());
}

/*Update once when submenu is opened*/
void WeaponWeaponsMenu::UpdateOnce() {}

/*Update while submenu is active*/
void WeaponWeaponsMenu::Update() {}

/*Background update*/
void WeaponWeaponsMenu::FeatureUpdate() {
	if (vars.rainbowCamo) RainbowCamo();
	//if (vars.giveallweaponsloop) giveallweaponeverysesh();

}

/*Singleton*/
WeaponWeaponsMenu* _instance;
WeaponWeaponsMenu* WeaponWeaponsMenu::GetInstance() {
	if (_instance == nullptr) {
		_instance = new WeaponWeaponsMenu();
		_instance->Init();
		GetSubmenuHandler()->addSubmenu(_instance);
	}
	return _instance;
}
WeaponWeaponsMenu::~WeaponWeaponsMenu() { delete _instance; }